[window]

decorations = "None"
decorations_theme_variant = "Dark"
startup_mode = "Fullscreen"

[font]

normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"
size = 13

[cursor]

style.blinking = 'Always'
blink_interval = 200
blink_timeout = 0
